version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: Moscow178
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  spring:
    build:
      context: .
      dockerfile: assets/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres: